### ISSUE TITLE
QuickMon access to F5 via Jumpbox

### ISSUE THREAD

**Issue by faheemarshad** [renatoferreirarenatoferreira/quickmon#1]
Hi, Thanks for your nice effort. I was trying to use QuickMon to monitor one my F5 appliance via Jumpbox. I can access the appliance via browser from the Jumpbox. But I am unable to access it via quickmon. The things i have tried so far

1- Configured SNMP on my appliance- added the allowed host in the configuration (My Jumpbox IP) of F5.
2- Configured SNMP v2 and also tried v3.
3- Added the host IP in QuickMon and dragged it to the tools area

But nothing happens on QuickMon. It is blank - no communication with F5

Am I missing something ????

Thanks

**Comment by renatoferreirarenatoferreira** [comment]
Are you sure that the UDP packets are reaching the F5 BIG-IP instance? It can be done by using tcpdump. Try it with the following parameters:
- _tcpdump -i 0.0 -n udp port 161_

It will also show you the correct IP address that is reaching the server, what will permit you to fix the allowed host configuration if required.

Are you trying to reach the SNMP service through the BIG-IP's management IP address? If not you may have to check your self IP port lockdown configuration.

Are you using the lastest QuickMon version? I have been fixing critical bugs in the lastest releases.

**Comment by faheemarshad** [comment]
Hi, This morning I tried again, but this time the drag and drop option is disabled. Its not responsive. The version that I am using is v0.5.1 64 bit. 

Also I am using F5 management IP to connect. 

I did tcpdump as well but packets are coming to Big IP.

**Comment by faheemarshad** [comment]
correction - packets are not coming*

**Comment by renatoferreirarenatoferreira** [comment]
Well.... It seems like you have a network connectivity issue there.

Attach here your quickmon.sqlite and I will check your configuration.

Another good point would be checking if the packets are leaving your computer. Some personal firewalls may block some application's traffic, mainly because QuickMon is not properly signed using a public CA (application signing certificates are expensive for open source purposes).

**Comment by renatoferreirarenatoferreira** [comment]
Did it work? I will close this issue.
